<?php

declare(strict_types=1);

namespace Application\DataMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180406111451 extends AbstractMigration
{

    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('INSERT INTO config_type (TYPE) VALUES ("int")');
        $this->addSql('INSERT INTO config_type (TYPE) VALUES ("string")');
        $this->addSql('INSERT INTO config_type (TYPE) VALUES ("boolean")');
        $this->addSql('INSERT INTO config_type (TYPE) VALUES ("double")');
        $this->addSql('INSERT INTO users_entrance_type (name) VALUES ("JOIN")');
        $this->addSql('INSERT INTO users_entrance_type (name) VALUES ("LEAVE")');
        $this->addSql('INSERT INTO clients_entrance_type (name) VALUES ("JOIN")');
        $this->addSql('INSERT INTO clients_entrance_type (name) VALUES ("LEAVE")');
        $this->addSql('INSERT INTO clients_entrance_type (name) VALUES ("DENIED_FULL")');
        $this->addSql('INSERT INTO clients_entrance_type (name) VALUES ("DENIED_CONFLICTIVE")');
        $this->addSql('INSERT INTO clients_entrance_type (name) VALUES ("FORCED_ACCESS")');
        $this->addSql('INSERT INTO users_manage_type (name) VALUES ("ADD")');
        $this->addSql('INSERT INTO users_manage_type (name) VALUES ("EDIT")');
        $this->addSql('INSERT INTO users_manage_type (name) VALUES ("DELETE")');
        $this->addSql('INSERT INTO conflict_reason_manage_type (name) VALUES ("ADD")');
        $this->addSql('INSERT INTO conflict_reason_manage_type (name) VALUES ("EDIT")');
        $this->addSql('INSERT INTO conflict_reason_manage_type (name) VALUES ("DELETE")');
        $this->addSql('INSERT INTO permission_list_manage_type (name) VALUES ("ADD")');
        $this->addSql('INSERT INTO permission_list_manage_type (name) VALUES ("EDIT")');
        $this->addSql('INSERT INTO permission_list_manage_type (name) VALUES ("DELETE")');
        $this->addSql('INSERT INTO rate_manage_type (name) VALUES ("ADD")');
        $this->addSql('INSERT INTO rate_manage_type (name) VALUES ("EDIT")');
        $this->addSql('INSERT INTO rate_manage_type (name) VALUES ("DELETE")');
        $this->addSql('INSERT INTO genders (name) VALUES ("M")');
        $this->addSql('INSERT INTO genders (name) VALUES ("F")');
        $this->addSql('INSERT INTO genders (name) VALUES ("NA")');
        $this->addSql('insert  into `config`(`config`,`value`, dataType) values  ("api_rate_limit_interval_s","20",1)');
        $this->addSql('insert  into `config`(`config`,`value`, dataType) values  ("api_rate_limit_rate","10",1)');
        $this->addSql('insert  into `config`(`config`,`value`, dataType) values  ("maxPersonsInRoom","1000",1)');
        $this->addSql('insert  into `config`(`config`,`value`, dataType) values  ("disco_name","Mi discoteca",2)');
        $this->addSql('insert  into `config`(`config`,`value`, dataType) values  ("recover_code_seconds_expire","600",1)');
        $this->addSql('insert  into `extra_config`(`config`,`value`) values  ("base64_logo","")');
        $this->addSql('insert  into `scm_config`(`config`,`value`) values  ("version","0.7.1")');
        $this->addSql('insert  into `clients_entrance_pricing`(trans_es,trans_en,`name`,`price`) values 
                    ("Gratis por RRPP", "Free by RRPP", "RRPP_FREE","0"),("Entrada por RRPP", "Entrance by RRPP", "RRPP_FLYER","5"),("Entrada general", "General entrance", "GENERAL","10"),
                    ("Invitado", "Guest", "GUEST","0"),("Empleado", "Worker", "INTERNAL_WORKER","0")');
        $this->addSql('insert  into `clients_ban_type`(`name`) values 
                      ("DISPUTES"), ("TOO_DRUNKED"), ("DRUGS_CONSUME"), ("AGGRESSIONS")');
        $this->addSql('insert  into `nationalities`(`name`) values ("ES")');
        $this->addSql('insert  into `permissions_list`(id,`list_key_name`) values (1,"BOSS"),(6,"SECURITY"),(3,"WAITER"),(4,"MARKETING"),(5,"RRPP_BOSS"),(2,"RRPP")');
        $this->addSql('insert  into `custom_translate_available_langs`(id,`lang_key`) values (1,"es"),(2,"en")');
        $this->addSql("insert  into `user_chat_status`(id,chat_status) values (3,'IDLE'),(2,'OFFLINE'),(1,'ONLINE');");
        $this->addSql("insert  into `nationalities`(`id`,`code`,`country`) values 
(1058,'AF','Afghanistan'),
(1059,'AL','Albania'),
(1060,'DZ','Algeria'),
(1061,'AS','American Samoa'),
(1062,'AD','Andorra'),
(1063,'AO','Angola'),
(1064,'AI','Anguilla'),
(1065,'AQ','Antarctica'),
(1066,'AG','Antigua And Barbuda'),
(1067,'AR','Argentina'),
(1068,'AM','Armenia'),
(1069,'AW','Aruba'),
(1070,'AU','Australia'),
(1071,'AT','Austria'),
(1072,'AZ','Azerbaijan'),
(1073,'BS','Bahamas'),
(1074,'BH','Bahrain'),
(1075,'BD','Bangladesh'),
(1076,'BB','Barbados'),
(1077,'BY','Belarus'),
(1078,'BE','Belgium'),
(1079,'BZ','Belize'),
(1080,'BJ','Benin'),
(1081,'BM','Bermuda'),
(1082,'BT','Bhutan'),
(1083,'BO','Bolivia'),
(1084,'BA','Bosnia And Herzegovina'),
(1085,'BW','Botswana'),
(1086,'BV','Bouvet Island'),
(1087,'BR','Brazil'),
(1088,'IO','British Indian Ocean Territory'),
(1089,'BN','Brunei Darussalam'),
(1090,'BG','Bulgaria'),
(1091,'BF','Burkina Faso'),
(1092,'BI','Burundi'),
(1093,'KH','Cambodia'),
(1094,'CM','Cameroon'),
(1095,'CA','Canada'),
(1096,'CV','Cape Verde'),
(1097,'KY','Cayman Islands'),
(1098,'CF','Central African Republic'),
(1099,'TD','Chad'),
(1100,'CL','Chile'),
(1101,'CN','China'),
(1102,'CX','Christmas Island'),
(1103,'CC','Cocos (keeling) Islands'),
(1104,'CO','Colombia'),
(1105,'KM','Comoros'),
(1106,'CG','Congo'),
(1107,'CD','Congo, The Democratic Republic Of The'),
(1108,'CK','Cook Islands'),
(1109,'CR','Costa Rica'),
(1110,'CI','Cote D\'ivoire'),
(1111,'HR','Croatia'),
(1112,'CU','Cuba'),
(1113,'CY','Cyprus'),
(1114,'CZ','Czech Republic'),
(1115,'DK','Denmark'),
(1116,'DJ','Djibouti'),
(1117,'DM','Dominica'),
(1118,'DO','Dominican Republic'),
(1119,'TP','East Timor'),
(1120,'EC','Ecuador'),
(1121,'EG','Egypt'),
(1122,'SV','El Salvador'),
(1123,'GQ','Equatorial Guinea'),
(1124,'ER','Eritrea'),
(1125,'EE','Estonia'),
(1126,'ET','Ethiopia'),
(1127,'FK','Falkland Islands (malvinas)'),
(1128,'FO','Faroe Islands'),
(1129,'FJ','Fiji'),
(1130,'FI','Finland'),
(1131,'FR','France'),
(1132,'GF','French Guiana'),
(1133,'PF','French Polynesia'),
(1134,'TF','French Southern Territories'),
(1135,'GA','Gabon'),
(1136,'GM','Gambia'),
(1137,'GE','Georgia'),
(1138,'DE','Germany'),
(1139,'GH','Ghana'),
(1140,'GI','Gibraltar'),
(1141,'GR','Greece'),
(1142,'GL','Greenland'),
(1143,'GD','Grenada'),
(1144,'GP','Guadeloupe'),
(1145,'GU','Guam'),
(1146,'GT','Guatemala'),
(1147,'GN','Guinea'),
(1148,'GW','Guinea-bissau'),
(1149,'GY','Guyana'),
(1150,'HT','Haiti'),
(1151,'HM','Heard Island And Mcdonald Islands'),
(1152,'VA','Holy See (vatican City State)'),
(1153,'HN','Honduras'),
(1154,'HK','Hong Kong'),
(1155,'HU','Hungary'),
(1156,'IS','Iceland'),
(1157,'IN','India'),
(1158,'ID','Indonesia'),
(1159,'IR','Iran, Islamic Republic Of'),
(1160,'IQ','Iraq'),
(1161,'IE','Ireland'),
(1162,'IL','Israel'),
(1163,'IT','Italy'),
(1164,'JM','Jamaica'),
(1165,'JP','Japan'),
(1166,'JO','Jordan'),
(1167,'KZ','Kazakstan'),
(1168,'KE','Kenya'),
(1169,'KI','Kiribati'),
(1170,'KP','Korea, Democratic People\'s Republic Of'),
(1171,'KR','Korea, Republic Of'),
(1172,'KV','Kosovo'),
(1173,'KW','Kuwait'),
(1174,'KG','Kyrgyzstan'),
(1175,'LA','Lao People\'s Democratic Republic'),
(1176,'LV','Latvia'),
(1177,'LB','Lebanon'),
(1178,'LS','Lesotho'),
(1179,'LR','Liberia'),
(1180,'LY','Libyan Arab Jamahiriya'),
(1181,'LI','Liechtenstein'),
(1182,'LT','Lithuania'),
(1183,'LU','Luxembourg'),
(1184,'MO','Macau'),
(1185,'MK','Macedonia, The Former Yugoslav Republic Of'),
(1186,'MG','Madagascar'),
(1187,'MW','Malawi'),
(1188,'MY','Malaysia'),
(1189,'MV','Maldives'),
(1190,'ML','Mali'),
(1191,'MT','Malta'),
(1192,'MH','Marshall Islands'),
(1193,'MQ','Martinique'),
(1194,'MR','Mauritania'),
(1195,'MU','Mauritius'),
(1196,'YT','Mayotte'),
(1197,'MX','Mexico'),
(1198,'FM','Micronesia, Federated States Of'),
(1199,'MD','Moldova, Republic Of'),
(1200,'MC','Monaco'),
(1201,'MN','Mongolia'),
(1202,'MS','Montserrat'),
(1203,'ME','Montenegro'),
(1204,'MA','Morocco'),
(1205,'MZ','Mozambique'),
(1206,'MM','Myanmar'),
(1207,'NA','Namibia'),
(1208,'NR','Nauru'),
(1209,'NP','Nepal'),
(1210,'NL','Netherlands'),
(1211,'AN','Netherlands Antilles'),
(1212,'NC','New Caledonia'),
(1213,'NZ','New Zealand'),
(1214,'NI','Nicaragua'),
(1215,'NE','Niger'),
(1216,'NG','Nigeria'),
(1217,'NU','Niue'),
(1218,'NF','Norfolk Island'),
(1219,'MP','Northern Mariana Islands'),
(1220,'NO','Norway'),
(1221,'OM','Oman'),
(1222,'PK','Pakistan'),
(1223,'PW','Palau'),
(1224,'PS','Palestinian Territory, Occupied'),
(1225,'PA','Panama'),
(1226,'PG','Papua New Guinea'),
(1227,'PY','Paraguay'),
(1228,'PE','Peru'),
(1229,'PH','Philippines'),
(1230,'PN','Pitcairn'),
(1231,'PL','Poland'),
(1232,'PT','Portugal'),
(1233,'PR','Puerto Rico'),
(1234,'QA','Qatar'),
(1235,'RE','Reunion'),
(1236,'RO','Romania'),
(1237,'RU','Russian Federation'),
(1238,'RW','Rwanda'),
(1239,'SH','Saint Helena'),
(1240,'KN','Saint Kitts And Nevis'),
(1241,'LC','Saint Lucia'),
(1242,'PM','Saint Pierre And Miquelon'),
(1243,'VC','Saint Vincent And The Grenadines'),
(1244,'WS','Samoa'),
(1245,'SM','San Marino'),
(1246,'ST','Sao Tome And Principe'),
(1247,'SA','Saudi Arabia'),
(1248,'SN','Senegal'),
(1249,'RS','Serbia'),
(1250,'SC','Seychelles'),
(1251,'SL','Sierra Leone'),
(1252,'SG','Singapore'),
(1253,'SK','Slovakia'),
(1254,'SI','Slovenia'),
(1255,'SB','Solomon Islands'),
(1256,'SO','Somalia'),
(1257,'ZA','South Africa'),
(1258,'GS','South Georgia And The South Sandwich Islands'),
(1259,'ES','Spain'),
(1260,'LK','Sri Lanka'),
(1261,'SD','Sudan'),
(1262,'SR','Suriname'),
(1263,'SJ','Svalbard And Jan Mayen'),
(1264,'SZ','Swaziland'),
(1265,'SE','Sweden'),
(1266,'CH','Switzerland'),
(1267,'SY','Syrian Arab Republic'),
(1268,'TW','Taiwan, Province Of China'),
(1269,'TJ','Tajikistan'),
(1270,'TZ','Tanzania, United Republic Of'),
(1271,'TH','Thailand'),
(1272,'TG','Togo'),
(1273,'TK','Tokelau'),
(1274,'TO','Tonga'),
(1275,'TT','Trinidad And Tobago'),
(1276,'TN','Tunisia'),
(1277,'TR','Turkey'),
(1278,'TM','Turkmenistan'),
(1279,'TC','Turks And Caicos Islands'),
(1280,'TV','Tuvalu'),
(1281,'UG','Uganda'),
(1282,'UA','Ukraine'),
(1283,'AE','United Arab Emirates'),
(1284,'GB','United Kingdom'),
(1285,'US','United States'),
(1286,'UM','United States Minor Outlying Islands'),
(1287,'UY','Uruguay'),
(1288,'UZ','Uzbekistan'),
(1289,'VU','Vanuatu'),
(1290,'VE','Venezuela'),
(1291,'VN','Viet Nam'),
(1292,'VG','Virgin Islands, British'),
(1293,'VI','Virgin Islands, U.s.'),
(1294,'WF','Wallis And Futuna'),
(1295,'EH','Western Sahara'),
(1296,'YE','Yemen'),
(1297,'ZM','Zambia'),
(1298,'ZW','Zimbabwe');");
        /* LISTAS DE PERMISOS PARA PERMISOS - GRUPOS DE PERMISOS. AL JEFE LE METEMOS T0DOS

        TODO
        $permissions =$em->getRepository('DataBundle:Permission')->findAll();
        foreach ($permissions as $permission) {
            $userPermission = new UserPermissions();
            $userPermission->setUser($user);
            $userPermission->setPermission($permission);
            $em->persist($userPermission);
            $em->flush();
        }*/
        $this->addSql("insert  into `permissions`(`action`) values 
                            ('VIEW_DASHBOARD'),
                            ('MANAGE_PROFILE'),
                            ('MANAGE_USERS'),
                            ('VIEW_ALL_USERS'),
                            ('VIEW_ROOM_USERS'),
                            ('VIEW_ROOM_CLIENTS'),
                            ('VIEW_ALL_CLIENTS'),
                            ('VIEW_MONETIZATION'),
                            ('VIEW_STATS'),
                            ('MANAGE_STOCK'),
                            ('MANAGE_MARKETING_PROMOS'),
                            ('MANAGE_MARKETING_EVENTS'),
                            ('MANAGE_MARKETING_PARTIES'),
                            ('MANAGE_CONFIG'),
                            ('SET_USER_CONFLICTIVE'),
                            ('SET_CLIENT_INFO'),
                            ('MANAGE_ROOM_CONFLICTS'),
                            ('MANAGE_ROOM_RATES'),
                            ('VIEW_SERVER_STATUS'),
                            ('SELL_STOCK'),
                            ('CHANGE_LOGO'),
                            ('MANAGE_PERMISSIONS'),
                            ('MANAGE_TRANSLATES'),
                            ('MANAGE_STOCK_TYPES'),
                            ('RECOVER_PASSWORD'),
                            ('USE_CHAT'),
                            ('LOGOUT');");
        $this->addSql('insert  into `permissions_lists`(`id_permission_id`,`id_list_id`) values 
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(2,1),
(2,2),
(2,3),
(2,4),
(2,5),
(2,6),
(3,1),
(4,1),
(4,6),
(5,1),
(5,6),
(6,1),
(6,2),
(6,3),
(6,4),
(6,5),
(6,6),
(7,1),
(7,4),
(7,6),
(8,1),
(8,4),
(9,1),
(9,4),
(9,5),
(9,6),
(10,1),
(10,4),
(11,1),
(11,4),
(12,1),
(12,4),
(13,1),
(13,4),
(14,1),
(15,1),
(15,6),
(16,1),
(16,2),
(16,5),
(17,1),
(17,6),
(18,1),
(18,4),
(19,1),
(20,1),
(20,3),
(21,1),
(22,1),
(23,1),
(24,1),
(24,4),
(25,1),
(25,2),
(25,3),
(25,4),
(25,5),
(25,6),
(26,1),
(26,2),
(26,3),
(26,4),
(26,5),
(26,6),
(27,1),
(27,2),
(27,3),
(27,4),
(27,5),
(27,6);');
        $this->addSql("
insert  into `custom_translate`(`key_id`,`lang_key_id`,`value`) values 
('CONFLICT.AGGRESSIONS',1,'Agresiones'),
('CONFLICT.AGGRESSIONS',2,'Agressions'),
('CONFLICT.DISPUTES',1,'Disputas'),
('CONFLICT.DISPUTES',2,'Disputes'),
('CONFLICT.DRUGS_CONSUMING',1,'Consumo de drogas'),
('CONFLICT.DRUGS_CONSUMING',2,'Drugs consuming'),
('CONFLICT.TOO_DRUNKED',1,'Consumo excesivo de alcohol'),
('EMAIL.POWEREDBY',1,'Local manejado por '),
('EMAIL.POWEREDBY',2,'Powered by '),
('EMAIL.RECOVERPASS.CONTENT',1,'Para proceder a recuperar tu cuenta, ingresa el código:'),
('EMAIL.RECOVERPASS.CONTENT',2,'Put this code inside the new form:'),
('EMAIL.RECOVERPASS.SENDNEW.CONTENT',1,'Aquí tienes tu nueva contraseña, podrás cambiarla una vez accedas al panel: '),
('EMAIL.RECOVERPASS.SENDNEW.CONTENT',2,'There goes your new password, you would change it after login: '),
('EMAIL.RECOVERPASS.SENDNEW.TITLE',1,'Nueva contraseña'),
('EMAIL.RECOVERPASS.SENDNEW.TITLE',2,'New password'),
('EMAIL.RECOVERPASS.TITLE',1,'Recupera tu contraseña'),
('EMAIL.RECOVERPASS.TITLE',2,'Recover password'),
('PERMISSION.IND.CHANGE_LOGO',1,'Cambiar logotipo'),
('PERMISSION.IND.LOGOUT',1,'Cerrar sesión'),
('PERMISSION.IND.MANAGE_CONFIG',1,'Modificar configuración'),
('PERMISSION.IND.MANAGE_MARKETING_EVENTS',1,'Modificar eventos (Marketing)'),
('PERMISSION.IND.MANAGE_MARKETING_PARTIES',1,'Modificar fiestas (marketing)'),
('PERMISSION.IND.MANAGE_MARKETING_PROMOS',1,'Modificar promociones (Marketing)'),
('PERMISSION.IND.MANAGE_PERMISSIONS',1,'Modificar grupos de permisos'),
('PERMISSION.IND.MANAGE_PROFILE',1,'Modificar perfil (propio)'),
('PERMISSION.IND.MANAGE_ROOM_CONFLICTS',1,'Modificar tipos de conflicto'),
('PERMISSION.IND.MANAGE_ROOM_RATES',1,'Modificar tarifas'),
('PERMISSION.IND.MANAGE_ROOM_THEME',1,'Modificar tema (web)'),
('PERMISSION.IND.MANAGE_STOCK',1,'Modificar inventario'),
('PERMISSION.IND.MANAGE_STOCK_TYPES',1,'Modificar tipos de inventario'),
('PERMISSION.IND.MANAGE_TRANSLATES',1,'Traducciones'),
('PERMISSION.IND.MANAGE_USERS',1,'Modificar trabajadores'),
('PERMISSION.IND.RECOVER_PASSWORD',1,'Restaurar contraseña (Personal)'),
('PERMISSION.IND.SELL_STOCK',1,'Vender inventario'),
('PERMISSION.IND.SET_CLIENT_INFO',1,'Recoger innformación de usuario en sala'),
('PERMISSION.IND.SET_USER_CONFLICTIVE',1,'Marcar usuario como conflictivo'),
('PERMISSION.IND.VIEW_ALL_CLIENTS',1,'Ver histórico de clientes'),
('PERMISSION.IND.VIEW_ALL_USERS',1,'Ver histórico trabajadores'),
('PERMISSION.IND.VIEW_DASHBOARD',1,'Ver estadísticas de sala (básicas)'),
('PERMISSION.IND.VIEW_MONETIZATION',1,'Ver flujo de caja'),
('PERMISSION.IND.VIEW_ROOM_CLIENTS',1,'Ver clientes en sala'),
('PERMISSION.IND.VIEW_ROOM_USERS',1,'Ver trabajadores en sala'),
('PERMISSION.IND.VIEW_SERVER_STATUS',1,'Ver estado del servidor'),
('PERMISSION.IND.VIEW_STATS',1,'Ver estadísticas'),
('PERMISSION.MARKETING',1,'Marketing'),
('PERMISSION.MARKETING',2,'Marketing'),
('PERMISSION.BOSS',1,'Jefe'),
('PERMISSION.BOSS',2,'Boss'),
('PERMISSION.RRPP',1,'Relaciones públicas'),
('PERMISSION.RRPP',2,'Public relations'),
('PERMISSION.RRPP_BOSS',1,'Jefe de relaciones públicas'),
('PERMISSION.RRPP_BOSS',2,'Public relations boss'),
('PERMISSION.SECURITY',1,'Seguridad'),
('PERMISSION.SECURITY',2,'Security'),
('PERMISSION.WAITER',1,'Camarero'),
('PERMISSION.WAITER',2,'Waiter');
('PERMISSION.IND.USE_CHAT',1,'Usar chat');
('PERMISSION.IND.USE_CHAT',2,'Use chat');
                        ");
    }

    public function down(Schema $schema)
    {
    }

}
