api_clients:
    channel: scm/clients
    handler:
        callback: 'clients.topic'
api_users:
    channel: scm/users
    handler:
        callback: 'users.topic'
api_userentrances:
    channel: scm/users_entrances
    handler:
        callback: 'entrance.users.topic'
api_clientsentrances:
    channel: scm/clients_entrances
    handler:
        callback: 'entrance.clients.topic'
api_clientsbans:
    channel: scm/clients_conflictive
    handler:
        callback: 'clients.bans.topic'
api_users_manage:
    channel: scm/users_manage
    handler:
        callback: 'manage.users.topic'
api_config_manage:
    channel: scm/config_manage
    handler:
        callback: 'manage.config.topic'
api_clients_extradata:
    channel: scm/clients_extradata
    handler:
        callback: 'extradata.client.topic'
api_logo:
    channel: scm/config_logo
    handler:
        callback: 'logo.config.topic'
api_conflictreasons:
    channel: scm/conflictreasons_manage
    handler:
        callback: 'manage.conflictreasons.topic'
api_rates:
    channel: scm/rates_manage
    handler:
        callback: 'manage.rates.topic'
api_translations:
    channel: scm/translations
    handler:
        callback: 'translations.topic'
auth_guard:
    channel: scm/auth
    handler:
        callback: 'auth.topic'
api_manage_permissions:
    channel: scm/permissions_manage
    handler:
        callback: 'permissionslist.manage.topic'