services:
    sockets.clients:
        class: WebSocketsBundle\Topic\ClientsTopic
    sockets.auth:
        class: WebSocketsBundle\Topic\AuthTopic
    sockets.users:
        class: WebSocketsBundle\Topic\UsersTopic
    sockets.clients.extradata:
        class: WebSocketsBundle\Topic\ClientsExtraDataTopic
    sockets.users.entrances:
        class: WebSocketsBundle\Topic\UsersEntranceTopic
    sockets.clients.entrances:
        class: WebSocketsBundle\Topic\ClientsEntranceTopic
    sockets.clients.bans:
        class: WebSocketsBundle\Topic\ClientsBansTopic
    sockets.users.manage:
        class: WebSocketsBundle\Topic\ManageUsersTopic
    sockets.config.manage:
        class: WebSocketsBundle\Topic\ManageConfigTopic
    sockets.conflictreasons.manage:
        class: WebSocketsBundle\Topic\ConflictReasonTopic
    sockets.rates.manage:
        class: WebSocketsBundle\Topic\RatesManageTopic
    sockets.config.logo:
        class: WebSocketsBundle\Topic\LogoConfigTopic
    sockets.translations:
        class: WebSocketsBundle\Topic\TranslationsTopic
    sockets.permissionslist.manage:
        class: WebSocketsBundle\Topic\PermissionsListTopic

    gos_web_socket_server.client_event.listener:
        class: WebSocketsBundle\EventListener\ConnectionListener
        tags:
            - { name: kernel.event_listener, event: 'gos_web_socket.client_connected', method: onClientConnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_disconnected', method: onClientDisconnect }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_error', method: onClientError }
            - { name: kernel.event_listener, event: 'gos_web_socket.server_launched', method: onServerStart }
            - { name: kernel.event_listener, event: 'gos_web_socket.client_rejected', method: onClientRejected }