imports:
    - { resource: config.yml }
parameters:
    database_host: 192.168.1.2
    database_port: 3306
    database_name: scm_disco
    database_user: scm
    database_password: Q5KOavC2VzpI
    mailer_transport: smtp
    mailer_host: mail.privateemail.com
    mailer_user: admin@scmnight.com
    mailer_password: e46936540OI
    mailer_encryption: ssl
    secret: crossewdfingersxd
    cors_allow_origin: 'https://www.scmnight.com'
    jwt_key_pass_phrase: g6GfdDs2453Ax
    websocket_host: scmnight.com
    websocket_port: 9846
    
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
twig:
    exception_controller: HandlingBundle:Main:error