# Login / Logout
session:
    type:     rest
    resource: RestBundle\Controller\SessionController
    prefix:   /
# Account recover
recover:
    type:     rest
    resource: RestBundle\Controller\RecoverController
    prefix:   /
# Users data
users:
    type:       rest
    resource:   RestBundle\Controller\UserController
    prefix:   /users
# Logged in user info
userinfo:
    type:       rest
    resource:   RestBundle\Controller\UserInfoController
    prefix:   /session
# Clients data
clients:
    type:       rest
    resource:   RestBundle\Controller\ClientController
    prefix:   /clients
# Config data
config:
    type:       rest
    resource:   RestBundle\Controller\ConfigController
    prefix:   /config
    